---

- name: Deploy services
  hosts: all
  tasks:

  - name: run command 
    picos_config: mode='cli_config' cmd='{{cmd}}'
    register: exec_result

  - name: Show execution result
    debug: var=exec_result.stdout_lines
