---
- name: Deploy services
  hosts: all
  tasks:
  - name: Transfer the script
    copy: src=./configs/set_snmp.conf dest=~/setconfig1.conf force=yes mode=0777

  - name: Activate the configuration
    picos_config: mode='config_load' cmd='~/setconfig1.conf'
    register: exec_result

  - name: Show execution result
    debug: var=exec_result.stdout_lines
